In [2]:
import torch

In [2]:
# [:, None, None, None]的作用
tensor = torch.tensor([1])
print(tensor.shape)
print(tensor)
expanded_tensor = tensor[:, None, None, None]
print(expanded_tensor.shape)
print(expanded_tensor)

torch.Size([1])
tensor([1])
torch.Size([1, 1, 1, 1])
tensor([[[[1]]]])


In [3]:
# 数据类型推断
beta = torch.linspace(1, 2, 10)
alpha = 1.- beta
print(alpha)
alpha = 1- beta
print(alpha)

tensor([ 0.0000, -0.1111, -0.2222, -0.3333, -0.4444, -0.5556, -0.6667, -0.7778,
        -0.8889, -1.0000])
tensor([ 0.0000, -0.1111, -0.2222, -0.3333, -0.4444, -0.5556, -0.6667, -0.7778,
        -0.8889, -1.0000])


In [4]:
tensor = torch.zeros(1, 3, 2, 4)

print("生成的张量：")
print(tensor)
print("张量的形状：", tensor.shape)

生成的张量：
tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]],

         [[0., 0., 0., 0.],
          [0., 0., 0., 0.]]]])
张量的形状： torch.Size([1, 3, 2, 4])


In [38]:
def pos_encoding(t, channels):
    inv_freq = 1.0 / (
        10000
        ** (torch.arange(0, channels, 2, device="cpu").float() / channels)
    )
    print(t.shape)
    print(inv_freq.shape)
    pos_enc_a = torch.sin(t.repeat(1, channels // 2) * inv_freq)
    print(pos_enc_a.shape)
    pos_enc_b = torch.cos(t.repeat(1, channels // 2) * inv_freq)
    pos_enc = torch.cat([pos_enc_a, pos_enc_b], dim=-1)
    return pos_enc

tensor = torch.Tensor([1])
new_tensor = pos_encoding(tensor, channels=256)
new_tensor

torch.Size([1])
torch.Size([128])
torch.Size([1, 128])


tensor([[8.4147e-01, 8.0196e-01, 7.6172e-01, 7.2141e-01, 6.8156e-01, 6.4256e-01,
         6.0469e-01, 5.6818e-01, 5.3317e-01, 4.9974e-01, 4.6795e-01, 4.3781e-01,
         4.0931e-01, 3.8242e-01, 3.5711e-01, 3.3332e-01, 3.1098e-01, 2.9004e-01,
         2.7043e-01, 2.5208e-01, 2.3492e-01, 2.1889e-01, 2.0391e-01, 1.8993e-01,
         1.7689e-01, 1.6473e-01, 1.5338e-01, 1.4281e-01, 1.3296e-01, 1.2378e-01,
         1.1522e-01, 1.0725e-01, 9.9833e-02, 9.2923e-02, 8.6488e-02, 8.0497e-02,
         7.4919e-02, 6.9726e-02, 6.4893e-02, 6.0393e-02, 5.6204e-02, 5.2306e-02,
         4.8678e-02, 4.5300e-02, 4.2157e-02, 3.9232e-02, 3.6509e-02, 3.3976e-02,
         3.1618e-02, 2.9423e-02, 2.7381e-02, 2.5480e-02, 2.3712e-02, 2.2066e-02,
         2.0534e-02, 1.9108e-02, 1.7782e-02, 1.6547e-02, 1.5399e-02, 1.4330e-02,
         1.3335e-02, 1.2409e-02, 1.1548e-02, 1.0746e-02, 9.9998e-03, 9.3056e-03,
         8.6595e-03, 8.0583e-03, 7.4989e-03, 6.9782e-03, 6.4938e-03, 6.0429e-03,
         5.6234e-03, 5.2330e

In [33]:
x = torch.tensor([[1, 2], [1, 2]])
print(x.shape)
print(x)
print(x.repeat(1, 1, 2, 3).shape)
print(x.repeat(1, 1, 2, 3))
print(x.repeat(1, 1, 1, 2, 3).shape)


torch.Size([2, 2])
tensor([[1, 2],
        [1, 2]])
torch.Size([1, 1, 4, 6])
tensor([[[[1, 2, 1, 2, 1, 2],
          [1, 2, 1, 2, 1, 2],
          [1, 2, 1, 2, 1, 2],
          [1, 2, 1, 2, 1, 2]]]])
torch.Size([1, 1, 1, 4, 6])


In [4]:
import torchvision
from torch.utils.data import DataLoader
def get_data():
    transforms = torchvision.transforms.Compose([
        torchvision.transforms.Resize(80),
        torchvision.transforms.RandomResizedCrop(64, scale=(0.8, 1.0)),
        torchvision.transforms.ToTensor(),
        torchvision.transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
    ])
    dataset = torchvision.datasets.ImageFolder(r"./data", transform=transforms)
    dataloader = DataLoader(dataset, batch_size=64, shuffle=True)
    return dataloader
data = get_data()

In [9]:
for batch in data:
    inputs, labels = batch
    print("Batch shape:", inputs.shape)

Batch shape: torch.Size([64, 3, 64, 64])
Batch shape: torch.Size([64, 3, 64, 64])
Batch shape: torch.Size([64, 3, 64, 64])
Batch shape: torch.Size([64, 3, 64, 64])
Batch shape: torch.Size([64, 3, 64, 64])


KeyboardInterrupt: 

In [1]:
from UNet import UNet
import torch
device = "cpu"
model = UNet(device=device)
t = torch.randn(2)
x = torch.randn(2, 3, 64, 64)
print(model(x, t).shape)

Down
torch.Size([2, 64, 64, 64])
torch.Size([2, 64, 32, 32])
ResNet
torch.Size([2, 64, 32, 32])
torch.Size([2, 128, 32, 32])
torch.Size([2, 128, 1, 1])
torch.Size([2, 128, 32, 32])
torch.Size([2, 128, 32, 32])
torch.Size([2, 128, 32, 32])
torch.Size([2, 128, 32, 32])
selfattention
torch.Size([2, 128, 32, 32])
torch.Size([2, 1024, 128])
torch.Size([2, 1024, 128])
torch.Size([2, 1024, 128])
torch.Size([2, 1024, 128])
torch.Size([2, 128, 32, 32])
torch.Size([2, 128, 32, 32])
Down
torch.Size([2, 128, 32, 32])
torch.Size([2, 128, 16, 16])
ResNet
torch.Size([2, 128, 16, 16])
torch.Size([2, 256, 16, 16])
torch.Size([2, 256, 1, 1])
torch.Size([2, 256, 16, 16])
torch.Size([2, 256, 16, 16])
torch.Size([2, 256, 16, 16])
torch.Size([2, 256, 16, 16])
selfattention
torch.Size([2, 256, 16, 16])
torch.Size([2, 256, 256])
torch.Size([2, 256, 256])
torch.Size([2, 256, 256])
torch.Size([2, 256, 256])
torch.Size([2, 256, 16, 16])
torch.Size([2, 256, 16, 16])
Down
torch.Size([2, 256, 16, 16])
torch.Size([2

In [ ]:
import torch
import tensorwatch as tw
from UNet import UNet # 这是我自己定义的一个网络
 
model = UNet()
tw.draw_model(model, [1, 3, 64, 64])